### PR TITLE
map2alm and alm2map

### LINKED ISSUE #20: some options for spherical harmonics
I see a few possible ways to get map2alm/alm2map into Healpix.jl.

1. Call FastTransforms.jl. This may require some coordination with the author -- I think HEALPix needs rings of both even and odd size? This has been discussed in the context of LibHealpix.jl. https://github.com/JuliaApproximation/FastTransforms.jl/issues/28
2. Wrap Libsharp ([Reinecke and Seljebotn 2013](http://arxiv.org/abs/1303.4945)), which I think some HEALPix implementations use. This is nice from a standards point of view, since we're also using Libsharp on rectangular pixelizations (plate carrée) in LSSTDESC/NaMaster and simonsobs/pixell. This would probably involve some C linker suffering and BinaryBuilder, maybe resulting in a LibSharp.jl which would depend on Healpix.jl.
3. Port map2alm from an existing HEALPix implementation into Healpix.jl. This would probably be the most work and also the slowest.

Finally, to get science done I'm currently just wrapping healpy through PyCall, which is not ideal but could be sufficient. 

Thoughts?

### PR DESCRIPTION
**Pull request by xzackli**
This pull request resolves #20 by adding map2alm and alm2map for both Map and PolarizedMap.

### CODE REVIEW

**Comment by xzackli** [comment]
d2e5a1cc30f48c94938234e41d8121328f8709be implements your suggestions 1 and 2, by specializing on Float64 for map2alm and alm2map. I've added tests for different map types.

**Comment by xzackli** [comment]
I agree about the versioning, it makes sense to release 3.0.0 with SHT support and drop those Julia versions < 1.3.

**Comment by xzackli** [comment]
Hey @ziotom78, your suggestions got me thinking about better organization based on dispatch. I've now reordered it substantially, and added comments and documentation throughout.

**Comment by ziotom78** [comment]
Looks good, thanks a lot @xzackli !

**Pull request merged**
