### PR TITLE
simple alm2cl

### PR DESCRIPTION
**Pull request by xzackli**
A derived product from a project of mine, alm2cl.

### CODE REVIEW

**Comment by ziotom78** [comment]
Great, thanks a lot @xzackli , this was something I really wanted to implement during this lockdown, but I am still struggling in finding the time to do so… May you please add some unit test to [`test/test_alm.jl`](https://github.com/ziotom78/Healpix.jl/blob/master/test/test_alm.jl)? (BTW, it's weird that codecov reports an *increase* in code coverage…)

**Comment by xzackli** [comment]
I had an indirect test in the SHT tests, but I've added a more specific test in the test_alm.jl.

**Comment by xzackli** [comment]
I'm having a hard time doing research in the lockdown too. It's part of why I'm writing some Julia-related PRs, the language is enjoyable enough to be kind of therapeutic.

**Comment by ziotom78** [comment]
Thanks a lot @xzackli, and take care!

**Pull request merged**
